### ISSUE TITLE
Upgrade Vue to v3

### ISSUE THREAD

**Issue by VoltanFr** [VoltanFr/memcheck#22]
To do only when [Bootstrap Vue](https://bootstrap-vue.org/) is available in a compatible version.
Check [this thread](https://github.com/bootstrap-vue/bootstrap-vue/issues/5196).

Relates to #23

**Comment by CodyEddings** [comment]
Is there a timeline on this?

**Comment by VoltanFr** [comment]
Hello @CodyEddings 
I don't really know more than what's available in the quoted thread.
My plan is to keep an eye an it and upgrade when possible.
Low priority for my project.
Thanks for chiming in.
Vincent

**Comment by CodyEddings** [comment]
Whoops, commented on the wrong thread. Apologies 😄

**Comment by VoltanFr** [comment]
No worries, it was funny to see someone interested in this single-developer project! (so far)

**Comment by VoltanFr** [comment]
Done in [this commit](https://github.com/VoltanFr/memcheck/commit/9afb586f9bc69666c849a21ec69added1e94910b)
