### ISSUE TITLE
Email address confirmation email considered dangerous

### ISSUE THREAD

**Issue by gregoiremahon** [VoltanFr/memcheck#237]
When you send an email address confirmation message while creating an account on MemCheck, it automatically goes into spam emails on gmail and is considered 'unsafe'.
To reproduce this problem, create a new account and look at the email sent to validate your email address.

**Comment by VoltanFr** [comment]
I have not fixed, but have improved the information to the user, specifying that the mail may be in the spam folder.
Fixing the spam problem probably needs that we have a domain name for MemCheck, so I'll tackle that later.
Poke @gregoiremahon
